### ISSUE TITLE
Team Ocicat Review

### ISSUE THREAD

**Issue by cod3smith** [santiagorodriguezbermudez/Piggy-App#1]
Great progress on your capstone project :smiley: :nerd_face: :nerd_face: :nerd_face: . Looks like it's coming together perfectly. Here are a few things you could improve:
- [x] Make the sidebar hidden until clicked on.
- [x] Fix the font size. 
- [x] Fix the horizontal scroll when sidebar is displayed.
- [x] Increase height of navbar.
- [x] Override form-control class.

Again, great work. Keep at it.
Happy coding. :technologist:

**Comment by santiagorodriguezbermudez** [comment]
Thanks for the comment :)
